/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkPdfRouteImport } from './routes/watermark-pdf'
import { Route as UpscaleImageRouteImport } from './routes/upscale-image'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as RotatePdfRouteImport } from './routes/rotate-pdf'
import { Route as RemoveBackgroundRouteImport } from './routes/remove-background'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as OrganizePdfRouteImport } from './routes/organize-pdf'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as HeicToJpgRouteImport } from './routes/heic-to-jpg'
import { Route as ConvertImageRouteImport } from './routes/convert-image'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as CompressImageRouteImport } from './routes/compress-image'
import { Route as IndexRouteImport } from './routes/index'

const WatermarkPdfRoute = WatermarkPdfRouteImport.update({
  id: '/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UpscaleImageRoute = UpscaleImageRouteImport.update({
  id: '/upscale-image',
  path: '/upscale-image',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatePdfRoute = RotatePdfRouteImport.update({
  id: '/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveBackgroundRoute = RemoveBackgroundRouteImport.update({
  id: '/remove-background',
  path: '/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizePdfRoute = OrganizePdfRouteImport.update({
  id: '/organize-pdf',
  path: '/organize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HeicToJpgRoute = HeicToJpgRouteImport.update({
  id: '/heic-to-jpg',
  path: '/heic-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertImageRoute = ConvertImageRouteImport.update({
  id: '/convert-image',
  path: '/convert-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImageRoute = CompressImageRouteImport.update({
  id: '/compress-image',
  path: '/compress-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/convert-image': typeof ConvertImageRoute
  '/heic-to-jpg': typeof HeicToJpgRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
  '/upscale-image': typeof UpscaleImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/convert-image': typeof ConvertImageRoute
  '/heic-to-jpg': typeof HeicToJpgRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
  '/upscale-image': typeof UpscaleImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/convert-image': typeof ConvertImageRoute
  '/heic-to-jpg': typeof HeicToJpgRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
  '/upscale-image': typeof UpscaleImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/convert-image'
    | '/heic-to-jpg'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/organize-pdf'
    | '/pdf-to-image'
    | '/pdf-to-word'
    | '/remove-background'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/tentang'
    | '/upscale-image'
    | '/watermark-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/convert-image'
    | '/heic-to-jpg'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/organize-pdf'
    | '/pdf-to-image'
    | '/pdf-to-word'
    | '/remove-background'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/tentang'
    | '/upscale-image'
    | '/watermark-pdf'
  id:
    | '__root__'
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/convert-image'
    | '/heic-to-jpg'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/organize-pdf'
    | '/pdf-to-image'
    | '/pdf-to-word'
    | '/remove-background'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/tentang'
    | '/upscale-image'
    | '/watermark-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressImageRoute: typeof CompressImageRoute
  CompressPdfRoute: typeof CompressPdfRoute
  ConvertImageRoute: typeof ConvertImageRoute
  HeicToJpgRoute: typeof HeicToJpgRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  MergePdfRoute: typeof MergePdfRoute
  OrganizePdfRoute: typeof OrganizePdfRoute
  PdfToImageRoute: typeof PdfToImageRoute
  PdfToWordRoute: typeof PdfToWordRoute
  RemoveBackgroundRoute: typeof RemoveBackgroundRoute
  RotatePdfRoute: typeof RotatePdfRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TentangRoute: typeof TentangRoute
  UpscaleImageRoute: typeof UpscaleImageRoute
  WatermarkPdfRoute: typeof WatermarkPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark-pdf': {
      id: '/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof WatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upscale-image': {
      id: '/upscale-image'
      path: '/upscale-image'
      fullPath: '/upscale-image'
      preLoaderRoute: typeof UpscaleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-pdf': {
      id: '/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof RotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-background': {
      id: '/remove-background'
      path: '/remove-background'
      fullPath: '/remove-background'
      preLoaderRoute: typeof RemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-pdf': {
      id: '/organize-pdf'
      path: '/organize-pdf'
      fullPath: '/organize-pdf'
      preLoaderRoute: typeof OrganizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heic-to-jpg': {
      id: '/heic-to-jpg'
      path: '/heic-to-jpg'
      fullPath: '/heic-to-jpg'
      preLoaderRoute: typeof HeicToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert-image': {
      id: '/convert-image'
      path: '/convert-image'
      fullPath: '/convert-image'
      preLoaderRoute: typeof ConvertImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-image': {
      id: '/compress-image'
      path: '/compress-image'
      fullPath: '/compress-image'
      preLoaderRoute: typeof CompressImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressImageRoute: CompressImageRoute,
  CompressPdfRoute: CompressPdfRoute,
  ConvertImageRoute: ConvertImageRoute,
  HeicToJpgRoute: HeicToJpgRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  MergePdfRoute: MergePdfRoute,
  OrganizePdfRoute: OrganizePdfRoute,
  PdfToImageRoute: PdfToImageRoute,
  PdfToWordRoute: PdfToWordRoute,
  RemoveBackgroundRoute: RemoveBackgroundRoute,
  RotatePdfRoute: RotatePdfRoute,
  SplitPdfRoute: SplitPdfRoute,
  TentangRoute: TentangRoute,
  UpscaleImageRoute: UpscaleImageRoute,
  WatermarkPdfRoute: WatermarkPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
