/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as CompressImageRouteImport } from './routes/compress-image'
import { Route as IndexRouteImport } from './routes/index'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImageRoute = CompressImageRouteImport.update({
  id: '/compress-image',
  path: '/compress-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/split-pdf': typeof SplitPdfRoute
  '/tentang': typeof TentangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-image'
    | '/split-pdf'
    | '/tentang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-image'
    | '/split-pdf'
    | '/tentang'
  id:
    | '__root__'
    | '/'
    | '/compress-image'
    | '/compress-pdf'
    | '/image-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-image'
    | '/split-pdf'
    | '/tentang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressImageRoute: typeof CompressImageRoute
  CompressPdfRoute: typeof CompressPdfRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  MergePdfRoute: typeof MergePdfRoute
  PdfToImageRoute: typeof PdfToImageRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-image': {
      id: '/compress-image'
      path: '/compress-image'
      fullPath: '/compress-image'
      preLoaderRoute: typeof CompressImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressImageRoute: CompressImageRoute,
  CompressPdfRoute: CompressPdfRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  MergePdfRoute: MergePdfRoute,
  PdfToImageRoute: PdfToImageRoute,
  SplitPdfRoute: SplitPdfRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
